# ----------------------------------------------------------
# description: Parallel tau brainstorming runs on default timesteps
# position: 99
# ----------------------------------------------------------
# Launches four SSP2 scenarios with the four tau brainstorming switches
# activated one at a time (and once in combination), with cfg$sequential
# set to FALSE so that each start_run() submits its Rscript submit.R
# subprocess in the background and returns immediately. The parent R
# script exits a few seconds after kicking off all four runs, leaving
# them to solve in parallel.
#
# Start from magpie_dev root with:
#   Rscript start.R runscripts=tau_brainstorm_parallel submit=direct
# or directly:
#   Rscript scripts/start/tau_brainstorm_parallel.R
#
# Scenarios:
#   T-C    Switch C on, cell-level adoption dampener from LPJmL
#          (f14_adoption.cs3 generated by tau_brainstorm_make_inputs.R)
#   T-D    Switch D on, cell-level ceiling from LPJmL
#          (f14_tau_ceiling.cs3 generated by tau_brainstorm_make_inputs.R)
#   T-AB   Switches A (maintenance cost=10) + B (concave exponent 0.7)
#          combined. Tests whether pairing cost-side and yield-side levers
#          avoids the cropland-expansion blow-up seen with TB alone.
#   T-ABCD All four switches simultaneously at moderate settings.
#
# Uses the default c_timesteps (inherited from config/default.cfg =
# "coup2100"), so each run solves 18 timesteps from y1995 to y2100 at
# roughly 5-year cadence. Expected wall-clock per run on local CONOPT4:
# ~2.5 h serial, but with sequential=FALSE all four launch concurrently.
#
# Requires modules/14_yields/input/f14_adoption.cs3 and
# modules/14_yields/input/f14_tau_ceiling.cs3 to exist (run
# scripts/start/tau_brainstorm_make_inputs.R first).

library(lucode2)
library(gms)

source("scripts/start_functions.R")
source("config/default.cfg")

# Shared settings
cfg$results_folder  <- "output/:title:"
cfg$force_replace   <- TRUE
cfg$force_download  <- FALSE
cfg$recalibrate     <- FALSE
cfg$recalibrate_landconversion_cost <- FALSE

# Key: run each start_run in the background so all scenarios launch in parallel
cfg$sequential      <- FALSE

# Sanity check — the cs3 inputs must exist or Switches C and D degenerate
# to the uniform fallback (α = 1, ceiling = 100 → mechanism inactive).
stopifnot(file.exists("modules/14_yields/input/f14_adoption.cs3"))
stopifnot(file.exists("modules/14_yields/input/f14_tau_ceiling.cs3"))

runs <- list(
  list(title = "tauBS_TC_lpj",
       config = list(s14_adoption_on = 1)),
  list(title = "tauBS_TD_lpj",
       config = list(s14_tau_degradation_on = 1)),
  list(title = "tauBS_TAB_cost10_exp07",
       config = list(s13_maintenance_cost = 10,
                     s14_tau_exponent_on  = 1,
                     s14_tau_exponent     = 0.7)),
  list(title = "tauBS_TABCD_all",
       config = list(s13_maintenance_cost   = 10,
                     s14_tau_exponent_on    = 1,
                     s14_tau_exponent       = 0.7,
                     s14_adoption_on        = 1,
                     s14_tau_degradation_on = 1))
)

for (r in runs) {
  message("\n===== Launching ", r$title, " =====")
  cfg$title <- r$title
  # Reset every switch so carry-over between iterations is explicit
  cfg$gms$s13_maintenance_cost   <- 0
  cfg$gms$s14_tau_exponent_on    <- 0
  cfg$gms$s14_tau_exponent       <- 1
  cfg$gms$s14_adoption_on        <- 0
  cfg$gms$s14_tau_degradation_on <- 0
  for (k in names(r$config)) cfg$gms[[k]] <- r$config[[k]]
  start_run(cfg, codeCheck = FALSE)
}

message("\n===== All four runs launched in the background =====")
message("Monitor with: ls output/tauBS_T*/full.log and tail each file")
